In [ ]:
#Name: Patrick Delaney, T-number: T00144648, Module:Advanced Scripting
#Previous basic csv file creation process to be used as a baseline for developing a varing length and
#size dataset file for future reading by the plotly api.

import csv


rowcounter= int(input("Please enter the number of employees with the company: "))

employeelist =[]
subname = ['EmployeeName','Income']
employeelist.append(subname)

for num in range(rowcounter):
    e_names = input("Please enter the employees name:")
    payment = input("Please enter the employees yearly income:")
    subvalues = [e_names, payment]
    print (subvalues)
    employeelist.append(subvalues)

print (employeelist)

with open('employeeincome.csv', 'w') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(employeelist)
csvFile.close()

In [2]:
import csv

heading_string = input("Please enter the titles of headings to be in the dataset(seperated by ','): ")
subheading = heading_string.split(", ")
dataset_list =[]
dataset_list.append(subheading)
print(subheading) # check if the heading have entered correctly

#Determine number of datasets to be included for the csv file
rowcounter= int(input("Please enter the number of employees with the company: "))
#iterate through based on the number of value groupd to be added
for numrow in range(rowcounter):
    subvalue = []
    colval = 0
    while colval < len(subheading): # A while loop to store values to prep for each row
        colval += 1
        empval = input(f"Please enter the employee {numrow} values for {colval} column: ")
        subvalue.append(empval)
    print(subvalue)
    #add the values to the dataset list to aline with the heading created
    dataset_list.append(subvalue)
    
print(dataset_list)
# use basic csv creation to store the dataset created into a readable format
with open('employeedetails.csv', 'w') as csvempFile:# open new file/existing file
    writer = csv.writer(csvempFile) # open the writer function on  csvfile
    writer.writerows(dataset_list) # write the dataset list to the csv file
csvempFile.close() #close the csv file in the process

Please enter the titles of headings to be in the dataset(seperated by ','): Name, Address, Town, Country, Phone, Income
['Name', 'Address', 'Town', 'Country', 'Phone', 'Income']
Please enter the number of employees with the company: 6
Please enter the employee 0 values for 1 column: Patrick
Please enter the employee 0 values for 2 column: Gallowsfield
Please enter the employee 0 values for 3 column: Tralee
Please enter the employee 0 values for 4 column: Ireland
Please enter the employee 0 values for 5 column: 0667123456
Please enter the employee 0 values for 6 column: 45000
['Patrick', 'Gallowsfield', 'Tralee', 'Ireland', '0667123456', '45000']
Please enter the employee 1 values for 1 column: Mary
Please enter the employee 1 values for 2 column: St. Brendans
Please enter the employee 1 values for 3 column: Tralee
Please enter the employee 1 values for 4 column: Ireland
Please enter the employee 1 values for 5 column: 06671654321
Please enter the employee 1 values for 6 column: 54000
['Mary', 'St. Brendans', 'Tralee', 'Ireland', '06671654321', '54000']
Please enter the employee 2 values for 1 column: Joseph
Please enter the employee 2 values for 2 column: Rock St.
Please enter the employee 2 values for 3 column: Mallow
Please enter the employee 2 values for 4 column: Ireland
Please enter the employee 2 values for 5 column: 033764859
Please enter the employee 2 values for 6 column: 63000
['Joseph', 'Rock St.', 'Mallow', 'Ireland', '033764859', '63000']
Please enter the employee 3 values for 1 column: Mark
Please enter the employee 3 values for 2 column: New Avenue
Please enter the employee 3 values for 3 column: New York
Please enter the employee 3 values for 4 column: USA
Please enter the employee 3 values for 5 column: 011449958432
Please enter the employee 3 values for 6 column: 59000
['Mark', 'New Avenue', 'New York', 'USA', '011449958432', '59000']
Please enter the employee 4 values for 1 column: Laura
Please enter the employee 4 values for 2 column: Toran End Rd
Please enter the employee 4 values for 3 column: Barcelona
Please enter the employee 4 values for 4 column: Spain
Please enter the employee 4 values for 5 column: 455976328
Please enter the employee 4 values for 6 column: 76000
['Laura', 'Toran End Rd', 'Barcelona', 'Spain', '455976328', '76000']
Please enter the employee 5 values for 1 column: Aisling
Please enter the employee 5 values for 2 column: Coise Coille
Please enter the employee 5 values for 3 column: Tralee
Please enter the employee 5 values for 4 column: Ireland
Please enter the employee 5 values for 5 column: 0667134985
Please enter the employee 5 values for 6 column: 30000
['Aisling', 'Coise Coille', 'Tralee', 'Ireland', '0667134985', '30000']
[['Name', 'Address', 'Town', 'Country', 'Phone', 'Income'], ['Patrick', 'Gallowsfield', 'Tralee', 'Ireland', '0667123456', '45000'], ['Mary', 'St. Brendans', 'Tralee', 'Ireland', '06671654321', '54000'], ['Joseph', 'Rock St.', 'Mallow', 'Ireland', '033764859', '63000'], ['Mark', 'New Avenue', 'New York', 'USA', '011449958432', '59000'], ['Laura', 'Toran End Rd', 'Barcelona', 'Spain', '455976328', '76000'], ['Aisling', 'Coise Coille', 'Tralee', 'Ireland', '0667134985', '30000']]